# managing data

In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from ast import literal_eval
import ast

csv_path = r'C:\Users\USER098\Documents\GitHub\Project\RecommendationsML\Data\tmdb_5000\tmdb_5000_credits.csv'
pd.set_option('display.max_colwidth', None)
df = pd.read_csv(csv_path)

df["cast"] = df["cast"].apply(ast.literal_eval)
df["crew"] = df["crew"].apply(ast.literal_eval)

df["cast_names"] = df["cast"].apply(
    lambda x: [actor["name"].replace(" ", " ") for actor in x[:3]]  
)

df["cast_id"] = df["cast"].apply(
    lambda x: " ".join(str(actor["cast_id"]) for actor in x[:3])
)

df["cast_id"] = df["cast_id"].apply(lambda x: x.split())

df["order"] = df["cast"].apply(
    lambda x: " ".join(str(actor["order"]) for actor in x[:3])
)

df["order"] = df["order"].apply(lambda x: x.split())

def get_director(x):
    for i in x:
        if i['job'] == 'Director':
            return i['name']
    return np.nan
    
df['director'] = df['crew'].apply(get_director)

df.drop(columns=["crew","cast"], inplace=True)

df.to_csv('Data/results/tmdb_credits_edited.csv', index=False)
df.head()

,movie_id,title,cast_names,cast_id,order,director
0,19995,Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[242, 3, 25]","[0, 1, 2]",James Cameron
1,285,Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]","[4, 5, 6]","[0, 1, 2]",Gore Verbinski
2,206647,Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[1, 14, 13]","[0, 1, 2]",Sam Mendes
3,49026,The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]","[2, 8, 5]","[0, 1, 2]",Christopher Nolan
4,49529,John Carter,"[Taylor Kitsch, Lynn Collins, Samantha Morton]","[5, 20, 7]","[0, 1, 2]",Andrew Stanton

In [28]:
#delete nan from data
csv_path = r'C:\Users\USER098\Documents\GitHub\Project\RecommendationsML\Data\results\tmdb_credits_edited.csv'
df = pd.read_csv(csv_path)

df['director'] = df['director'].fillna('')

df.to_csv('Data/results/tmdb_credits_edited.csv', index=False)

df.isnull().sum()

movie_id      0
title         0
cast_names    0
cast_id       0
order         0
director      0
dtype: int64

In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from ast import literal_eval
import ast

csv_path = r'C:\Users\USER098\Documents\GitHub\Project\RecommendationsML\Data\tmdb_5000\tmdb_5000_movies.csv'
pd.set_option('display.max_colwidth', None)
df = pd.read_csv(csv_path)

df.drop(columns=["keywords","budget","homepage","production_countries",
                 "revenue","spoken_languages","tagline","vote_count",
                "title","original_language","runtime","status"], inplace=True)

df["genres"] = df["genres"].apply(ast.literal_eval)
df["production_companies"] = df["production_companies"].apply(ast.literal_eval)

df["genres"] = df["genres"].apply(
    lambda x: " ".join(actor["name"].replace(" ", "") for actor in x[:3])
)

df["genres"] = df["genres"].apply(lambda x: x.split())

df["production_companies"] = df["production_companies"].apply(
    lambda x: [company["name"].replace(" ", " ") for company in x[:3]]  # top 3 firmy
)

df.to_csv('Data/results/tmdb_movies_edited.csv', index=False)
df.head(1)

,genres,id,original_title,overview,popularity,production_companies,release_date,vote_average
0,"[Action, Adventure, Fantasy]",19995,Avatar,"In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",150.437577,"[Ingenious Film Partners, Twentieth Century Fox Film Corporation, Dune Entertainment]",2009-12-10,7.2

In [30]:
#delete nan from data
csv_path = r'C:\Users\USER098\Documents\GitHub\Project\RecommendationsML\Data\results\tmdb_movies_edited.csv'
df = pd.read_csv(csv_path)

df['overview'] = df['overview'].fillna('')
df['release_date'] = df['release_date'].fillna('')

df.to_csv('Data/results/tmdb_movies_edited.csv', index=False)

df.isnull().sum()

genres                  0
id                      0
original_title          0
overview                0
popularity              0
production_companies    0
release_date            0
vote_average            0
dtype: int64

In [31]:
csv_path = r'C:\Users\USER098\Documents\GitHub\Project\RecommendationsML\Data\results\tmdb_movies_edited.csv'
df_movies = pd.read_csv(csv_path)

csv_path1 = r'C:\Users\USER098\Documents\GitHub\Project\RecommendationsML\Data\results\tmdb_credits_edited.csv'
df_credits = pd.read_csv(csv_path1)

df = df_movies.merge(df_credits, left_on='id', right_on='movie_id')
df.drop(columns=['movie_id','original_title','order'], inplace=True)

df.to_csv('Data/results/conected_data.csv', index=False)
df.head(1)

#order chyba nie ma znaczenia bo zawsze bierze 3 pierwszych
# original_title powtorka

,genres,id,overview,popularity,production_companies,release_date,vote_average,title,cast_names,cast_id,director
0,"['Action', 'Adventure', 'Fantasy']",19995,"In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",150.437577,"['Ingenious Film Partners', 'Twentieth Century Fox Film Corporation', 'Dune Entertainment']",2009-12-10,7.2,Avatar,"['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver']","['242', '3', '25']",James Cameron

In [32]:
csv_path1 = r'C:\Users\USER098\Documents\GitHub\Project\RecommendationsML\Data\results\conected_data.csv'
df_credits = pd.read_csv(csv_path1)

df['overview'] = df['overview'].fillna('')
df['release_date'] = df['release_date'].fillna('')
df['director'] = df['overview'].fillna('')

df.to_csv('Data/results/tmdb_movies_edited.csv', index=False)
df.isnull().sum()

genres                  0
id                      0
overview                0
popularity              0
production_companies    0
release_date            0
vote_average            0
title                   0
cast_names              0
cast_id                 0
director                0
dtype: int64

In [33]:
import ast

def combine_features(row):
    director = row['director'].replace(" ", "") if isinstance(row['director'], str) else ""
    overview = row['overview'] if isinstance(row['overview'], str) else ""
    
    try:
        genres = ast.literal_eval(row['genres'])
    except:
        genres = []
    
    try:
        production_companies = [name.replace(" ", "") for name in ast.literal_eval(row['production_companies'])]
    except:
        production_companies = []
    
    try:
        cast_names = [name.replace(" ", "") for name in ast.literal_eval(row['cast_names'])]
    except:
        cast_names = []

    try:
        year = str(pd.to_datetime(row['release_date']).year)
    except:
        year = ""
    
    return " ".join(genres) + " " + director + " ".join(cast_names) + " ".join(production_companies) + " " + overview + " " + year

df['tags'] = df.apply(combine_features, axis=1)

df.to_csv('Data/results/final.csv', index=False)

df.head(1)

,genres,id,overview,popularity,production_companies,release_date,vote_average,title,cast_names,cast_id,director,tags
0,"['Action', 'Adventure', 'Fantasy']",19995,"In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",150.437577,"['Ingenious Film Partners', 'Twentieth Century Fox Film Corporation', 'Dune Entertainment']",2009-12-10,7.2,Avatar,"['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver']","['242', '3', '25']","In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.","Action Adventure Fantasy Inthe22ndcentury,aparaplegicMarineisdispatchedtothemoonPandoraonauniquemission,butbecomestornbetweenfollowingordersandprotectinganaliencivilization.SamWorthington ZoeSaldana SigourneyWeaverIngeniousFilmPartners TwentiethCenturyFoxFilmCorporation DuneEntertainment In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. 2009"

In [34]:
csv_path1 = r'C:\Users\USER098\Documents\GitHub\Project\RecommendationsML\Data\results\conected_data.csv'
df_credits = pd.read_csv(csv_path1)

df.isnull().sum()

genres                  0
id                      0
overview                0
popularity              0
production_companies    0
release_date            0
vote_average            0
title                   0
cast_names              0
cast_id                 0
director                0
tags                    0
dtype: int64

# Recommendations concept

In [10]:
# from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

cv = TfidfVectorizer(
    max_features=20000,
    stop_words='english',
    ngram_range=(1,2)
)

# cv = CountVectorizer(max_features=5000, stop_words='english')

vectors = cv.fit_transform(df['tags']).toarray()

similarity = cosine_similarity(vectors)

def recommend(movie_title):
    movie_index = df[df['title'] == movie_title].index[0]
    distances = list(enumerate(similarity[movie_index]))
    distances = sorted(distances, key=lambda x: x[1], reverse=True)[1:6]  # top 5 podobnych
    for i in distances:
        print(df.iloc[i[0]]['title'])

In [11]:
recommend("Avatar")

Dragonball Evolution
Eragon
The Inhabited Island
Live Free or Die Hard
The Book of Life

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

csv_path = r'C:\Users\USER098\Documents\GitHub\Project\RecommendationsML\Data\results\final.csv'
df = pd.read_csv(csv_path)

cv = TfidfVectorizer(
    max_features=20000,
    stop_words='english',
    ngram_range=(1,2)
)

vectors = cv.fit_transform(df['tags']).toarray()

def recommend(tag):
    tag_vector= cv.transform([tag])

    similarity = cosine_similarity(tag_vector,vectors)

    distances = list(enumerate(similarity[0]))
    
    distances = sorted(distances, key=lambda x: x[1], reverse=True)[:5]  
    for i in distances:
        print(df.iloc[i[0]]['title'])

tag="Action ScienceFiction Thriller ТимурБекмамбетов ChrisPratt RebeccaFerguson KaliReis AtlasEntertainment AmazonMGMStudios Bazelevs In the near future, a detective stands on trial accused of murdering his wife. He has ninety minutes to prove his innocence to the advanced AI Judge he once championed, before it determines his fate. 2026"

tag1="Action Crime Drama Thriller 杨子 成龍 张子枫 梁家輝 iQIYIPictures TaoPiaoPiao HairunPicturesCompany DongFangChenXiang Macau Police brings the tracking expert police officer out of retirement to help catch a dangerous group of professional thieves. 2025"

tag2="Drama Romance МихаилВайнберг ВероникаЖуравлёва ДаниэльВегас АляМайер AllMediaAStartCompany STARTStudio SverdlovskFilmStudio High school student Polina is saved from bullying at her new school and makes a deal with the main bully Bars: he must pretend to be her boyfriend and protect her, and she must do everything he says. During this game, the couple develops real feelings, but her family and classmates have reasons to separate the lovers. 2026"

print("1")
recommend(tag)

print("2")
recommend(tag1)

print("3")
recommend(tag2)

1
The Life of David Gale
The Hurricane
Sleep Dealer
Freeze Frame
The Fugitive
2
I Am Wrath
Street Kings
Kiss of the Dragon
Demonic
Triple 9
3
Mean Girls
The New Guy
Dumb and Dumberer: When Harry Met Lloyd
Detention of the Dead
Ed and His Dead Mother

# Recomendations test

In [20]:
print()